services:
  elancestvous:
    image: ghcr.io/thacac/elancestvous-nextjs-16:latest
    container_name: elancestvous
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-proxy
      - traefik.http.routers.elancestvous.rule=Host(`elancestvous.fr`,`www.elancestvous.fr`)
      - traefik.http.routers.elancestvous.entrypoints=websecure
      - traefik.http.routers.elancestvous.tls=true
      - traefik.http.routers.elancestvous.tls.certresolver=letsencrypt
      - traefik.http.services.elancestvous.loadbalancer.server.port=3000

networks:
  traefik-proxy:
    name: traefik-proxy
    external: true
