services:
  app:
    image: ghcr.io/thacac/elancestvous-nextjs-16:latest
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - app
    networks:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    # Lancé à la demande via infra/renew.sh (cron sur le host)

networks:
  web:
    driver: bridge
