services:
  app:
    image: ghcr.io/thacac/elancestvous-nextjs-16:latest
    container_name: elancestvous
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - web


  nginx:
    image: nginx:alpine
    container_name: elancestvous_nginx
    restart: unless-stopped
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - web
      - traefik-proxy
    labels:
      - traefik.enable=true
      # Remplace par tes domaines
      - traefik.http.routers.elancestvous.rule=Host(`elancestvous.fr`,`www.elancestvous.fr`)
      - traefik.http.routers.elancestvous.entrypoints=websecure
      - traefik.http.routers.elancestvous.tls=true
      - traefik.http.routers.elancestvous.tls.certresolver=letsencrypt
      - traefik.http.services.elancestvous.loadbalancer.server.port=80


networks:
  web:
    driver: bridge
  traefik-proxy:
    external: true
